### ISSUE TITLE
Please improve and cache the result of list_app

### ISSUE THREAD

**Issue by chihchun** [Cypresslin/UbunTuTuMKII#116]
1) Please put the command in one script, and push to the machine so that we don't need to run adb many times.
2) Please cache the result of list app.

**Comment by Cypresslin** [comment]
Hi chihchun,

so for 1, it's still too slow for them?
and for 2, why they want this cached, for speed concern or for sorting (issue #31) ?

Thanks!

**Comment by chihchun** [comment]
mainly on speed, it takes a few more seconds to scan the app list.
