### ISSUE TITLE
Unable to capture the file share event to other apps

### ISSUE THREAD

**Issue by Cypresslin** [Cypresslin/UbunTuTuMKII#130]
We can detect the file import event, but not the export one, this is the pattern:

> [pid 18775] sendmsg(17, {msg_name(0)=NULL, msg_iov(2)=[{"l\1\0\1M\0\0\0D\0\0\0\211\0\0\0\1\1o\0\1\0\0\0/\0\0\0\0\0\0\0\6\1s\0\37\0\0\0com.ubuntu.content.dbus.Service\0\2\1s\0\37\0\0\0com.ubuntu.content.dbus.Service\0\3\1s\0\21\0\0\0CreateShareToPeer\0\0\0\0\0\0\0\10\1g\0\3sss\0\0\0\0\0\0\0\0", 160}, {"\r\0\0\0messaging-app\0\0\0%\0\0\0com.ubuntu.gallery_gallery_2.9.1.1322\0\0\0\10\0\0\0pictures\0", 77}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 237

Test case:
open gallery, select a pic and try to share it to another app.

**Comment by gavin-lin** [comment]
Fixed by #137.
